# Generated by Django 4.0.5 on 2022-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='jop_type',
            field=models.CharField(choices=[('FULL_TIME', 'FULL_TIME'), ('PART_TIME', 'PART_TIME')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
