# Generated by Django 4.0.5 on 2022-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jop_jop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
