# Generated by Django 4.0.5 on 2022-06-26 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='job_img',
            field=models.FileField(default='', upload_to='jobs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
            preserve_default=False,
        ),
    ]
