# Generated by Django 4.0.5 on 2022-07-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jop_job_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
